version: '3'
services:
  rabbit:
   container_name: rabbit
   image: rabbitmq:management-alpine
   ports:
   - 5672:5672
   - 15672:15672

  mysql:
   container_name: mysql
   image: mysql
   ports:
   - 3306:3306
   environment:
    MYSQL_DATABASE: my_schema
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_ROOT_HOST: '%'
    MYSQL_USER: user
    MYSQL_PASSWORD: pass


  spring-jpa:
   container_name: spring-jpa
   build: .
   ports:
      - 8081:8080
   depends_on:
    - rabbit
    - mysql


  spring-jpastream:
   container_name: spring-jpastream
   build: .
   ports:
      - 8082:8080
   depends_on:
    - rabbit
    - mysql


  spring-jdbc:
   container_name: spring-jdbc
   build: .
   ports:
      - 8083:8080
   depends_on:
    - rabbit
    - mysql
      
      
  spring-batch:
   container_name: spring-batch
   build: .
   ports:
      - 8084:8080
   depends_on:
    - rabbit
    - mysql
      
  prometheus:
   container_name: prometheus
   image: prom/prometheus
   ports:
   - 9090:9090
   volumes:
   - ./prometheus.yml:/etc/prometheus/prometheus.yml
   command:
      - '--config.file=/etc/prometheus/prometheus.yml'   
   depends_on:
    - spring-batch
    - spring-jpa
    - spring-jpastream
    - spring-jdbc
   
  grafana:
   container_name: grafana
   image: grafana/grafana
   ports:
   - 3000:3000      
   depends_on:
    - prometheus  